name: "build"
on: [push]
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Check Docker changes
        id: container-changed-files
        uses: tj-actions/changed-files@v11.5
        with:
          files: |
            ./containers/Dockerfile
            ./containers/env.base.yml
      - name: Build Docker image
        if: steps.container-changed-files.outputs.any_changed == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: ghcr.io/${{ github.repository }}:v0.0.0, ghcr.io/${{ github.repository }}:latest
      - name: 'Install Nextflow'
        uses: stracquadaniolab/gh-action-setup-nextflow@v0.2.0
      - name: 'Testing Nextflow pipeline with test profile'
        run: |
          chmod +x bin/*
          nextflow run . -profile test,ci,docker      
      - name: Push image to GitHub container registry
        if: startsWith(github.event.ref, 'refs/tags')
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}:v0.0.0, ghcr.io/${{ github.repository }}:latest